### ISSUE TITLE
Investigate Backend Tech (CMS)

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#1]
Node vs Rails vs PHP, joomla vs wordpress etc.

**Comment by iamnbutler** [comment]
MEAN is one option: http://mean.io/#!/

**Comment by rosszurowski** [comment]
Limitations:
- Needs to have a way for users to get content in there easily (rich text editor?)
- Needs to be fast

**Comment by rosszurowski** [comment]
[Koa](http://koajs.com) was the Node framework mentioned within the meeting.

**Comment by iamnbutler** [comment]
Rails is an option:
- Simple security
- Lots of plugins easy to use
- Well supported

**Comment by iamnbutler** [comment]
I think it may be worth not dismissing using Parse right away. The getting started guide makes it look very simple to work with data: https://parse.com/docs/js/guide#hosting

I'm going to dig into it further.

**Comment by rosszurowski** [comment]
It looks like it's just an ORM/data-store. I think with Parse we'd still need to write a back-end of some kind. Mind confirming/denying this?

Also, with Parse, would we be able to run custom queries (say, for analytics)?

**Comment by iamnbutler** [comment]
Parse is built as an analytics platform, so I'm sure getting custom analytics wouldn't be an issue. Your first question is what I'm trying to figure out.

**Comment by iamnbutler** [comment]
So with Parse out of the picture I'd probably be leaning towards Rails. Any additional thoughts?

**Comment by rosszurowski** [comment]
I've been exploring Node/Koa and I think it might work better than I let on in the meeting. Putting together a little demo for when we meet next week. We can evaluate then?

**Comment by iamnbutler** [comment]
:+1:

**Comment by iamnbutler** [comment]
Re:API. If we did go with rails, this might be useful: https://www.youtube.com/watch?v=36M2BSA2LYk

**Comment by rosszurowski** [comment]
Going with Node/Koa.
