### ISSUE TITLE
ASAP Standalone site for ysdn2016.com

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#10]
Until we have a URL based on the show name, we need to get a landing page set up on ysdn2016.com. This should include social media updates and a email field that people can opt in to email transmissions/digital invite.

**Comment by rosszurowski** [comment]
If someone wants to design something but doesn't know how or doesn't want to develop it, I'm totally down to develop this.

**Comment by kvngco** [comment]
@kvng

**Comment by iamnbutler** [comment]
Here is a (not very amazing) example:
<img width="1280" alt="screen shot 2015-10-11 at 7 41 11 pm" src="https://cloud.githubusercontent.com/assets/1714999/10522126/7ddc55dc-7341-11e5-8c48-a5277dcac1bb.png">

**Comment by Emmersonic** [comment]
Site is up @ http://ysdn2016.com/
