### ISSUE TITLE
Mobile Homepage Intro Animation Tweak

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#100]
@mileeco another we should look at

I think what Michelle said about removing logo makes sense if we're keeping the one in the grid there.
Some thoughts:
- have http://ysdn2016.com/shapes/ the block instead without logo
- grid should align to edges of body margins
- fill white gaps flanking logo with dots

![screen shot 2016-04-05 at 16 34 51](https://cloud.githubusercontent.com/assets/3757807/14297444/bcf9be42-fb4c-11e5-8cbc-321a96798964.png)

**Comment by mileeco** [comment]
This is for @iamnbutler

**Comment by iamnbutler** [comment]
The solution for this will depend on #99.
