### ISSUE TITLE
Mobile Work – subcategory search ui tweaks and not functioning

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#101]
- Add divider as in mocks to help cue that you're searching amongst all the works and not within the selected bucket (divider hits where the subcategories start disappearing)
- tighten gap between search and subcategory
- search doesn't seem to be working

![screen shot 2016-04-05 at 16 42 42](https://cloud.githubusercontent.com/assets/3757807/14297574/900c5e34-fb4d-11e5-854b-70468ce3a8c6.png)

**Comment by Emmersonic** [comment]
@rosszurowski Did you want me to take this back now that I'm done with workshop?

**Comment by rosszurowski** [comment]
@emmersonic Sure. If you can handle this that'd be great. I'm finishing up event page stuff and then moving onto a backlog of other tasks.
