### ISSUE TITLE
(mobile) Sponsors page shapes

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#103]
Can we separate the shapes that appear on the header on Sponsors page (mobile) 🙊
... and we should also bring the header up slightly so it matches the rest of the pages.

![image](https://cloud.githubusercontent.com/assets/8468476/14306069/4fac7efc-fb91-11e5-9820-63e71063faba.png)

**Comment by rosszurowski** [comment]
Whoops. I fixed the spacing, but shapes are still on you @emmersonic.
