### ISSUE TITLE
Project index categories on tablet size is right aligned?

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#105]
:| Not sure if this is intentional but I realized that the alignment changes to the right when it's on tablet size. I think it should always be left aligned to be consistent??

http://cl.ly/1h1A2H273E0B

**Comment by Emmersonic** [comment]
Oh. At one point I heard we were going with C https://invis.io/RW6TE8UF7

**Comment by Emmersonic** [comment]
@rosszurowski Any reason why you closed this?

**Comment by rosszurowski** [comment]
@Emmersonic because I fixed it in a9bf104
