### ISSUE TITLE
Meet the Cast Instagram Feed often repeats

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#106]
The Instagram feed often doubles or triples on both desktop and mobile. Back to normal on refresh.

**Comment by iamnbutler** [comment]
I'm not sure what is causing this, @mileeco seemed to have the same problem. Try checking in incognito as well and see if it makes any difference. It might be a weird caching issue.

**Comment by kvngco** [comment]
It must be a caching issue then. Stopped duplicating when going into incognito

**Comment by rosszurowski** [comment]
If one of you figures out how to reproduce this, let me know.

**Comment by mileeco** [comment]
I had two people mention this to me yesterday (unfortunately they were snapchats so I couldn't screenshot). Told them to refresh then it was gone then. I know they've been on ysdn2016.com site before but it was previous landing page...

Not sure what's causing this ;__;

**Comment by iamnbutler** [comment]
Yeah seems like this is an existing bug out there, I've never found a way to reproduce it though... 😅
