### ISSUE TITLE
Event info full site link always take you to work page? 

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#109]
I noticed that if you go to event information page from "attend the grad show" button, and click "see full site" to go back, they take you to work page and not the page you were previously on. I noticed this for buttons on sponsors, home, and student pages.

**Comment by rosszurowski** [comment]
Ah, yeah, I had swapped it around for development but forgot to put it back.

**Comment by rosszurowski** [comment]
Should be fixed in https://github.com/ysdn-2016/ysdn-2016.github.io/commit/4fa34c9920c1f19ff47466365a5a464eae1166bd
