### ISSUE TITLE
Investigate Parse

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#11]
Pricing, etc

**Comment by iamnbutler** [comment]
Looks like you can use both React and Backbone.js with Parse.
JS Guide: https://parse.com/docs/js/guide#objects
React + Parse: https://github.com/ParsePlatform/ParseReact

From what I can understand, Parse pretty much fills the role of the backend entirely outside of security.

**Comment by iamnbutler** [comment]
<img width="335" alt="screenshot 2015-10-15 03 04 57" src="https://cloud.githubusercontent.com/assets/1714999/10506801/910e063a-72e9-11e5-9754-113a9edc87d1.png">

Looks like Parse is free up to 30 requests per second. The monthly cost is also calculated on an hourly basis, so we would only be paying extra for super high-load times, which we would only have 2 of: people uploading work and during the actual show.

**Comment by iamnbutler** [comment]
I started working through a [tutorial](http://code.tutsplus.com/tutorials/get-started-building-your-blog-with-parsejs-working-with-data--cms-22047) for setting up a basic cms with Parse. Other than one silly issue that took me a while to fix, it seems pretty straight forward. It utilizes [Handlebars](http://handlebarsjs.com/) for templating, but it looks like [Underscore](http://underscorejs.org/#template) and [Mustache](http://mustache.github.io/) are also options.

I haven't yet explored how Parse handles files. I'm not sure that it would be an effective solution for deploying video.

The repo I was working with: https://github.com/iamnbutler/parse-test

**Comment by iamnbutler** [comment]
I'm going to hold off on pursuing this further until backend has time to discuss options.

**Comment by rosszurowski** [comment]
Why hold off? Are you comfortable making a yes/no recommendation for Parse based on what you learned from your trial?

**Comment by iamnbutler** [comment]
Probably not. It seems difficult to problem-solve as there are not a lot of community resources, and I think we would run into issues where we have to split up data and content and host data elsewhere.

I think overall MEAN or Rails would be better options. Parse is probably more ideal for small projects.

**Comment by rosszurowski** [comment]
Ok. Gonna close this out then.
