### ISSUE TITLE
Microsoft Edge - Map doesn't load

### ISSUE THREAD

**Issue by Emmersonic** [ysdn-2016/ysdn-2016.github.io#114]
![image](https://cloud.githubusercontent.com/assets/6530910/14337377/42764cea-fc3b-11e5-8883-76621a00bf98.png)

**Comment by rosszurowski** [comment]
"Getting to the show"
"Getting to the show"

**Comment by mileeco** [comment]
Omg I just realized that :| maybe it can be Venue Location?

**Comment by mileeco** [comment]
Venue location \* ... but maybe it doesn't carry the same tone

**Comment by rosszurowski** [comment]
Having two headers of them in there is just an implementation detail: The mocks only show second header for desktop sizes. No need to find another title for the first header, I've gone ahead and hid it to match the mocks.
