### ISSUE TITLE
Microsoft Edge - Shows scrollbars when not needed -.-

### ISSUE THREAD

**Issue by Emmersonic** [ysdn-2016/ysdn-2016.github.io#115]
![image](https://cloud.githubusercontent.com/assets/6530910/14337527/af5c2d38-fc3c-11e5-8256-6e7c9ef1dad7.png)

**Comment by mileeco** [comment]
microsoft edge is such a jerk

**Comment by Emmersonic** [comment]
![sigh](https://cloud.githubusercontent.com/assets/6530910/14340162/c50bbd9a-fc52-11e5-850a-4b5492eb6589.gif)
(ノ ゜Д゜)ノ ︵ ┻━┻

**Comment by Emmersonic** [comment]
Fixed!
