### ISSUE TITLE
COPY FIXES (and like two line-height fix)

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#116]
Did final thorough check of all the copy on the site. Only minor changes. One thing that I mentioned before that I think that got slipped was changing "The Liberty Grand" to "the Liberty Grand" in all the footers. Liberty Grand <- that's the name and even their site has it written like that. I think student profile is the only page that has this changed.

_Heads up DON'T follow the copy that's on InVision. They're not updated to the latest cause we've been making a lot of quick changes lately. If you need to ask about copy message me._

**Home**
![screenshot-staging ysdn2016 com 2016-04-06 21-12-04](https://cloud.githubusercontent.com/assets/8468476/14337489/678e9914-fc3c-11e5-920d-7671c1b8a512.png)
![screenshot-staging ysdn2016 com 2016-04-06 21-11-44](https://cloud.githubusercontent.com/assets/8468476/14337490/6933ffde-fc3c-11e5-86fd-6c2d969d91bd.png)

**Project Index**

![screenshot-staging ysdn2016 com 2016-04-06 21-14-17](https://cloud.githubusercontent.com/assets/8468476/14337529/b2a4c4aa-fc3c-11e5-9a46-57b816229a16.png)

**Work pages (both case study and regular)**

![screenshot-staging ysdn2016 com 2016-04-06 21-05-20](https://cloud.githubusercontent.com/assets/8468476/14337531/b8eb47d0-fc3c-11e5-8b12-e2bc1bbf176b.png)

**Student Index**

Emily's suggestion:
![screenshot-staging ysdn2016 com 2016-04-06 20-57-12](https://cloud.githubusercontent.com/assets/8468476/14337537/c705f662-fc3c-11e5-994d-8aa78beb2845.png)

We should add ellipses to all to anticipate:
![screenshot-staging ysdn2016 com 2016-04-06 20-57-12](https://cloud.githubusercontent.com/assets/8468476/14337543/d6ce2b50-fc3c-11e5-8c8e-1a0699d30318.png)
![screenshot-staging ysdn2016 com 2016-04-06 20-57-16](https://cloud.githubusercontent.com/assets/8468476/14337545/d8a480d2-fc3c-11e5-983d-5cae9b55cfc7.png)

Search result message:
![screenshot-staging ysdn2016 com 2016-04-06 20-54-54](https://cloud.githubusercontent.com/assets/8468476/14337547/e9a02c10-fc3c-11e5-8617-c5fe9a160219.png)

Footer change:
![screenshot-staging ysdn2016 com 2016-04-06 21-10-18](https://cloud.githubusercontent.com/assets/8468476/14337549/f4a3e782-fc3c-11e5-97b7-fc191b6cb810.png)

**Sponsors:**

![screenshot-staging ysdn2016 com 2016-04-06 21-08-39](https://cloud.githubusercontent.com/assets/8468476/14337553/074b1388-fc3d-11e5-837e-78db33e99d23.png)

**About**

![screenshot-staging ysdn2016 com 2016-04-06 20-07-55](https://cloud.githubusercontent.com/assets/8468476/14337563/17668f90-fc3d-11e5-9307-f08312ecd8d0.png)

![screenshot-staging ysdn2016 com 2016-04-06 21-07-50](https://cloud.githubusercontent.com/assets/8468476/14337558/0e985d1c-fc3d-11e5-8a71-a8e3f869cb37.png)

**Event Info Page**

![screenshot-staging ysdn2016 com 2016-04-06 19-55-40](https://cloud.githubusercontent.com/assets/8468476/14337568/1f206b5c-fc3d-11e5-9ea2-0a6a831d59ee.png)
_*by 'this' I meant the address_

**Comment by Emmersonic** [comment]
@mileeco Addressed all of these with the exception of the "...!" addition. I think it's a little weird to mix those both.

**Comment by mileeco** [comment]
@emmersonic Hmm then I think we should just have it as ellipses. Ending it with exclamation mark to me feels like it's the end, even though it says "almost there"

**Comment by Emmersonic** [comment]
I read it as excitement. **Almost there!** but I can do just ellipses.

**Comment by mileeco** [comment]
@Emmersonic GAHHHH my screenshot not added properly (I swear I thought I checked). Sorry! Just one more:

![screenshot-staging ysdn2016 com 2016-04-06 20-56-29](https://cloud.githubusercontent.com/assets/8468476/14338713/2296531e-fc47-11e5-998e-d19105248559.png)

this is what I meant by Emily's change, the same screenshot got added twice -_-

**Comment by Emmersonic** [comment]
@mileeco Fixed!

**Comment by mileeco** [comment]
@emmersonic thank you you da best!!!!!

**Comment by mileeco** [comment]
@emmersonic Also noticed that the copy change hasn't been made for home... is that something @iamnbutler needs to change??

**Comment by Emmersonic** [comment]
@mileeco Haha, nope, I just forgot to save that file. Should be up in a minute.
