### ISSUE TITLE
Event page header collapses into single line and overlaps with content on the left at 1905px+

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#118]
Not high-pri. Just noticed that if you load event info page on thunderbolt screens (can easily get above 1905px width) the header line collapses to single line
![screenshot-staging ysdn2016 com 2016-04-07 02-25-18](https://cloud.githubusercontent.com/assets/8468476/14342526/3a867316-fc68-11e5-81f7-7a6a2a632a2f.png)

**Comment by rosszurowski** [comment]
Fixed in b9738e8, thanks for catching this!
