### ISSUE TITLE
Add student identifier to profile page to allow for individual adjustments (height, hiding, etc)

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#119]
Heads cut off for a few students (the taller ones)... Also noticed that the copy on the left is not middle-aligned vertically, but that can be tackled post launch.

![screenshot-staging ysdn2016 com 2016-04-07 02-51-58](https://cloud.githubusercontent.com/assets/8468476/14342972/d8516f8a-fc6b-11e5-978e-1261a33ec2c7.png)
![screenshot-staging ysdn2016 com 2016-04-07 02-51-42](https://cloud.githubusercontent.com/assets/8468476/14342973/d85b9fc8-fc6b-11e5-9b81-ceb9a0611095.png)

**Comment by iamnbutler** [comment]
Is this a complete list? I have to figure out the exact height we want this at. How bad is it if someone's head gets close to the nav?

**Comment by iamnbutler** [comment]
I increased the header height a bit. Let me know if it is too much, or if there are still cases that are too tall. we may need to bump a few people up/down specifically in the css, which would not be too hard, just a bit extra on dev time.

**Comment by mileeco** [comment]
@iamnbutler Went through all the students again and nope, everything looks great now!

I didn't see this yesterday, but Jinah's photo looks "broken". I know it's cause she didn't get her photo taken, but can we just take it out for hers then? I'll figure out what we can put there post-launch. Thanks!

![screenshot-staging ysdn2016 com 2016-04-07 14-16-54](https://cloud.githubusercontent.com/assets/8468476/14361987/86554340-fccb-11e5-9c6d-0a0e7912811a.png)

**Comment by iamnbutler** [comment]
Ahhh I really wish we had just tracked her down 😞 Yeah I'll have to add an student identifer to the page then, which means iI can do some height-based adjustments. Since her page is so unfinished in general I wouldn't worry too much about it.

**Comment by mileeco** [comment]
Sounds good!!!

**Comment by rosszurowski** [comment]
Oh, I inadvertently resolved this in 42ec71e. I'll leave this open in case we want to revisit the image.

![screen shot 2016-04-07 at 10 26 44 pm](https://cloud.githubusercontent.com/assets/303731/14372565/dab9773c-fd0f-11e5-9cbe-ca6933558518.png)

**Comment by iamnbutler** [comment]
I think this is done. Can re-open if issues still exist.
