### ISSUE TITLE
How do we ensure site will run for X amount of time?

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#12]
- Is digital locker an option?
- Can we develop a plan for keeping this and future years sites up?

**Comment by Emmersonic** [comment]
@iamnbutler http://ysdngradshow.com is hosted by sheridan college, so we should look into that.

**Comment by rosszurowski** [comment]
Gonna bring this up at the next exec meeting with Myles.

**Comment by iamnbutler** [comment]
Maybe relevant: [EC2 Pricing](http://www.ec2instances.info/)

**Comment by rosszurowski** [comment]
Taylor and I brought it up with Myles, and it sounds like York/Sheridan won't be hosting this. So it's on us to keep the site up. With that in mind, we should keep hosting costs as minimal as possible, and probably purchase any domains for several years out.
