### ISSUE TITLE
Student photo not centered on mobile

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#122]
Not high-pri, but I realized they're not centered on mobile! Just wanted to mark it here so we can fix it sometime
![image](https://cloud.githubusercontent.com/assets/8468476/14367234/d099d286-fce4-11e5-8516-0d61b5f4bfae.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14367235/d0af85fe-fce4-11e5-984f-53097bc9df11.png)

**Comment by iamnbutler** [comment]
Yeah this is weird, I had this issue but some were centered and some were not. Think it depends on the pose. I gotta look.

**Comment by rosszurowski** [comment]
Centred most of the really bad ones in https://github.com/ysdn-2016/ysdn-2016.github.io/commit/10acb0f18624ea55e80abf90e0f81b5ea30b5f8f. Message me on Slack if you see others that need fixing.
