### ISSUE TITLE
Project category header type --> fix to semibold weight

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#123]
Not that important... but it does bother me that this isn't the same weight as all other headers on the site. Can we update this to semi-bold please, thanks!!

Sorry to keep picking on things ;--;

![screenshot 2016-04-07 17 33 11](https://cloud.githubusercontent.com/assets/8468476/14367617/fca139f8-fce6-11e5-902c-1002f6e54823.png)
![screenshot 2016-04-07 17 33 08](https://cloud.githubusercontent.com/assets/8468476/14367618/fcacffae-fce6-11e5-9a95-8bbe89d822c3.png)

**Comment by Emmersonic** [comment]
How did you even spot the difference between Medium and semibold? 0.o I'll fix that

**Comment by Emmersonic** [comment]
Fixed
