### ISSUE TITLE
Thoughts on this copy fix? ;--; sorry

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#124]
I JUST noticed this and this is my bad.. so sorry!! I missed the word "Graduating" before "Class" in the second one. The word 'graduating' isn't necessary, but we should keep the two consistent (so either "Graduating class of 2016 presents The Intermission" or "Class of 2016 presents The Intermission"). Or if you think this doesn't matter we can leave it as it is.

![screenshot-staging ysdn2016 com 2016-04-07 17-40-42](https://cloud.githubusercontent.com/assets/8468476/14367814/29d7a460-fce8-11e5-9e63-af657f5d90b3.png)
![screenshot-staging ysdn2016 com 2016-04-07 17-40-46](https://cloud.githubusercontent.com/assets/8468476/14367825/2c202fa8-fce8-11e5-9de5-1ca8db1f021c.png)

**Comment by iamnbutler** [comment]
I'll grab this.

**Comment by rosszurowski** [comment]
Fixed in aa0f15f. @mileeco, mind confirming that you're comfortable with it on staging and then closing this out? Only difference is that the text wrap changes.

**Comment by mileeco** [comment]
Yep the change is good, thanks! Just a couple of things I noticed @rosszurowski:

Can we put a space between Design's and Class:

![screenshot-staging ysdn2016 com 2016-04-12 02-43-33](https://cloud.githubusercontent.com/assets/8468476/14451867/74aa8656-0058-11e6-9cc7-693bfaeaef5d.png)

Is there also a way to prevent this awkward line break?:

![screenshot-staging ysdn2016 com 2016-04-12 02-43-49](https://cloud.githubusercontent.com/assets/8468476/14451883/926644e6-0058-11e6-9fbb-67ada433c0b4.png)
