### ISSUE TITLE
"About" and "Sponsor" copy errors

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#126]
gratitude~_~_~*~

<img width="765" alt="screen shot 2016-04-07 at 21 34 39" src="https://cloud.githubusercontent.com/assets/3757807/14371751/acab89ea-fd08-11e5-803d-5d792056041b.png">

**Comment by kvngco** [comment]
"The Intermission is the graduating class of 2016's reflection on the last four years and and celebrations and hopes for the future."
to
"The Intermission is a celebration of the graduating class of 2016; it is a reflection on our past four years and our hopes for the future."

<img width="700" alt="screen shot 2016-04-07 at 21 37 41" src="https://cloud.githubusercontent.com/assets/3757807/14371805/fcd2d8ce-fd08-11e5-8c55-88a3279f4984.png">

**Comment by rosszurowski** [comment]
Closed in 38473b4
