### ISSUE TITLE
Logo Disappears on Home Page (Safari)

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#128]
After the animation, the logo in the header stays white, making it invisible.
![white](https://cloud.githubusercontent.com/assets/303731/14401741/2c36033e-fdea-11e5-87d4-25c35f5e4426.gif)

**Comment by iamnbutler** [comment]
Hmm if it is just the logo it might not like animating SVG elements with css animation...
