### ISSUE TITLE
Better "Event Information" language

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#129]
Apparently several people have gotten confused by the "Attend the Event" language, specifically in buttons on the home page and footer. People have mentioned that they weren't sure where to register, and that when they hit the "attend the event" button there wasn't form to fill out.

![screen shot 2016-04-09 at 12 43 21 pm](https://cloud.githubusercontent.com/assets/303731/14404960/6602c7f2-fe51-11e5-8320-2d1674276676.png)

I'd pin this confusion on the fact that many people might consider a grad show an event to register for (the Carleton Industrial Design program, for instance, requires registration), and the button doesn't alleviate that impression.

Maybe something like "Grad Show Information" or (I know this is what we had initially) "Event Information"

**Comment by Emmersonic** [comment]
I think this could also be improved by just stating that no registration/RSVP is required in the event page. I did something similar in the emails sent to industry. <img width="688" alt="screen shot 2016-04-09 at 12 51 49 pm" src="https://cloud.githubusercontent.com/assets/6530910/14404979/ec56d5fa-fe51-11e5-8fe3-0df23df2b44e.png">

**Comment by rosszurowski** [comment]
I think including something like this ^ would resolve any confusion, but it'd be nice if the buttons didn't give that impression in the first place either.

**Comment by mileeco** [comment]
Agreed to both. I think we changed to this because "Event Information" in ribbon wasn't clear to a few that I showed when it still had "Event Information" (they were like "what event"? though, they knew this was for grad show. I think they're used to hearing "grad show" instead). It also sounds a bit dry imo...

But I think we can still use that for button since it always has copy above that talks about the grad show... (maybe it's ok to have different copy for ribbon and button). I'd prefer something like "See Event Details" than "Event Information". I'll think of something else for event ribbon, or we can revisit the ideas Kevin had previously.

**Comment by mileeco** [comment]
I think this will help make it clearer? Discussed with Kevin and Nathan separately. For ribbon, either first or second! (I think we're leaning more towards first, but thought maybe including "The Intermission" is necessary so it doesn't feel too disconnected)

![events-cta-changes 2x](https://cloud.githubusercontent.com/assets/8468476/14408478/b389c0a2-fec4-11e5-8ba1-b9bbb799152c.jpg)

**Comment by rosszurowski** [comment]
That's super clear. I'll swap it out with the first option. Thanks @mileeco!

**Comment by mileeco** [comment]
Thanks! I forgot to mention Kevin suggested changing "see full site" to "view full site" so it's consistent!! @rosszurowski

**Comment by kvngco** [comment]
A few tweaks:

1) make "view event details" black

<img width="1328" alt="screen shot 2016-04-10 at 16 54 33" src="https://cloud.githubusercontent.com/assets/3757807/14413050/2629e074-ff3d-11e5-8d62-35ba10cf981b.png">

2) "see full site" to "view full site" on both mobile and desktop

<img width="305" alt="screen shot 2016-04-10 at 16 54 39" src="https://cloud.githubusercontent.com/assets/3757807/14413054/395044a4-ff3d-11e5-8b87-951646cbb359.png">

**Comment by kvngco** [comment]
Another one: take out "liberty grand" on smaller widths to avoid overlapping, or keep it "toronto · April 19" throughout.

<img width="625" alt="screen shot 2016-04-10 at 16 59 56" src="https://cloud.githubusercontent.com/assets/3757807/14413068/d6d78174-ff3d-11e5-9060-1c71c8a20539.png">

**Comment by mileeco** [comment]
@kvngco Can it change to just April 19 when it starts overlapping? I think "Liberty Grand" should be in there if we want to include location. Just having Toronto feels weird/confusing, especially to the industry here in Toronto who heard about the program already. Having just Toronto doesn't really provide any information imo (is it in downtown Toronto? near York campus? midtown?) so I'd say remove it when it starts overlapping and just have the date instead.

**Comment by mileeco** [comment]
I just realized I made that mistake in my own mock – meant to include "Liberty Grand" in there (was working off old file 😓)

**Comment by rosszurowski** [comment]
Ah, thanks for catching. (Sorry for all these sloppy fixes 😦 )

Shouldn't it be "Liberty Grand • April 19" given that most of our visitors are already in Toronto? Or, if both options are contentious, maybe just "April 19"?

**Comment by rosszurowski** [comment]
Whoa. The page just refreshed and I saw @mileeco's comment. I'll switch it to just "April 19" then. Thanks!

**Comment by mileeco** [comment]
~ A wild comment appeared ~

**Comment by mileeco** [comment]
Wait just 19th for all though?? :/ Can we still include the location at bigger window size?

**Comment by rosszurowski** [comment]
Yes. Sorry if it wasn't clear. It'll be "Liberty Grand, Toronto • April 19" at larger sizes, then "April 19" at smaller sizes.

**Comment by rosszurowski** [comment]
@kvngco Just pushed the tweaks to staging. Mind confirming that it's as-expected? Feel free to close if it's good.

**Comment by kvngco** [comment]
Hmm. I'd argue for the other side where Toronto is more important to show, so it'd be "Grad Show Toronto · April 19" on smaller.

Because we most likely will be getting more traffic from outside of Toronto once we submit to site inspiration links or social sharing, knowing that we're based in Toronto without having to click is nice to have. Others have it hosted on their school site, so that's clear. We have ysdn in the url, and it's branded as "The Intermission".

**Comment by kvngco** [comment]
Also needs to say "View Full Site" on mobile, too!

**Comment by rosszurowski** [comment]
Derp 😑 

Fixed mobile too in https://github.com/ysdn-2016/ysdn-2016.github.io/commit/31c6504172e7b92db6656108f60b82768e59e598

**Comment by kvngco** [comment]
omg gh issue reactions

**Comment by rosszurowski** [comment]
@kvngco, re: this comment

> Because we most likely will be getting more traffic from outside of Toronto once we submit to site inspiration links or social sharing…

I'm just trying to find the analytics from last year to check if this is accurate.

But would putting Toronto there even be helpful for those people? If they're in Vancouver, they probably won't be looking to attend, right? Seems like that communication would more appropriately live on the home page. Like, "we're students from YSDN, a Toronto-based design program" in that introductory block.

**Comment by kvngco** [comment]
Yeah. What you suggested is preferable. That would solve it on mobile, too, where unless you click event, there's no mention of location of our program or event.

**Comment by kvngco** [comment]
This probably is a non-issue. They'd click and find out. I'm probably just being very picky ha

**Comment by rosszurowski** [comment]
Hmm. I can't find the log-in details at the moment, so I can't check how the Toronto/non-Toronto distribution pans out.

I don't think it's a non-issue. The site currently does require some context before viewing, which isn't ideal. I'll open up a new issue for us to track communicating that the program is Toronto-based.

PS: @kvngco, if this task is done on staging, mind closing it out?

**Comment by mileeco** [comment]
Agreed witn @rosszurowski. I don't think event ribbon would be the place to discover that information, feels unnecessary and not that helpful.

**Comment by mileeco** [comment]
We can mention it in about page - but tbh I feel like they'd find out pretty easily on event details page.
