### ISSUE TITLE
Physical Categories description mentions physical computing.

### ISSUE THREAD

**Issue by Emmersonic** [ysdn-2016/ysdn-2016.github.io#131]
<img width="1268" alt="screen shot 2016-04-09 at 9 33 38 pm" src="https://cloud.githubusercontent.com/assets/6530910/14407530/e0d30a98-fe9a-11e5-8644-cabe73618428.png">
<img width="483" alt="screen shot 2016-04-09 at 9 33 29 pm" src="https://cloud.githubusercontent.com/assets/6530910/14407531/e0d5053c-fe9a-11e5-9106-ffc3afa1c875.png">
Description on homepage mentions 'physical computing' when that subcategory is actually under Interactive & Motion.

**Comment by mileeco** [comment]
Oh I thought physical computing fell under physical design (thought this was discussed before). If that's the case, let's just change it to another subcategory?

**Comment by mileeco** [comment]
Related, we have two subcategories named product design. 
![screenshot-ysdn2016 com 2016-04-10 01-33-45](https://cloud.githubusercontent.com/assets/8468476/14408290/6bd272b6-febc-11e5-843a-92eae83fa261.png)
![screenshot-ysdn2016 com 2016-04-10 01-33-39](https://cloud.githubusercontent.com/assets/8468476/14408291/6bd40c02-febc-11e5-94ab-8143b2a16a6b.png)

Thoughts on how we should handle this?? I guess it's still clear cause they fall under different parent categories, but it'd still be ideal to use different names.

**Comment by rosszurowski** [comment]
Fixed @emmersonic's bug in https://github.com/ysdn-2016/ysdn-2016.github.io/commit/91e03c74273ade747bd10d5b2fedcb9197866800.

Distinguishing the product designs by top level category wasn't accidental—I think that's the terminology people are familiar with. Open to revisiting the names though. You're thinking just spelling it out further? "Physical Product Design" "Digital Product Design"?

**Comment by mileeco** [comment]
Yeah! I'd prefer having them like that. It does get pretty long but I think it's definitely clearer...
