### ISSUE TITLE
Desktop Event – Sidebar ghost link too long at breakpoint

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#134]
<img width="594" alt="screen shot 2016-04-10 at 02 03 47" src="https://cloud.githubusercontent.com/assets/3757807/14413059/69cdcc14-ff3d-11e5-86c6-cf383b3da564.png">

**Comment by rosszurowski** [comment]
A fix is up now on staging. Mind confirming then closing out?

**Comment by kvngco** [comment]
good on staging!
