### ISSUE TITLE
Change Facebook link on sponsors page

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#136]
A friend was asking why Facebook link on sponsors page links to their profile (I think he was creeped out a little). I clicked it and realized it redirects to my profile too. Not sure what's happening here, but can we link it to "facebook.com"?

**Comment by rosszurowski** [comment]
Haha, that was me being sneaky. Too creepy?

**Comment by Emmersonic** [comment]
I can't believe someone actually clicked that in the first place.

**Comment by iamnbutler** [comment]
Yeahhhh thats a little creepy

**Comment by mileeco** [comment]
🌚

**Comment by rosszurowski** [comment]
Closed in fef5c42
