### ISSUE TITLE
Mobile Menu – Can Still Scroll with Overlay

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#137]
It shows a white gap where the chrome used to be, and then continues scrolling haha. Can we kill scrolling unless they click the overlay, or the menu bar?

![img_9709](https://cloud.githubusercontent.com/assets/3757807/14425955/3f594a36-ffb9-11e5-8dcc-c17480253ad4.PNG)

**Comment by rosszurowski** [comment]
Just pushed this to staging. Mind confirming @kvngco?

**Comment by kvngco** [comment]
Awesome 💃
