### ISSUE TITLE
Desktop Home – Navigation is against black bar for smaller vw

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#138]
Fine for other pages; behaves like this on Chrome, Safari

<img width="801" alt="screen shot 2016-04-11 at 07 50 00" src="https://cloud.githubusercontent.com/assets/3757807/14426105/62484a14-ffba-11e5-93e5-73db5e9fd777.png">

**Comment by rosszurowski** [comment]
@kvngco Mind elaborating on this issue? I'm not sure I can tell what you're talking about here. Does the bar not turn white? Or is it the fact that the bar is still black when you scroll down the page that's the problem?

**Comment by kvngco** [comment]
Here's a screencast of the issue:
1) Seems like the animation is going on, but it doesn't show on this vw
2) Bar stays black even after animation is finished (you can see the flashing)

![screen capture on 2016-04-11 at 10-02-42](https://cloud.githubusercontent.com/assets/3757807/14429790/e593c74c-ffcc-11e5-9375-17e5f973971a.gif)

**Comment by iamnbutler** [comment]
This is likely an side effect of `animation-delay`. It seems to not work occasionally when window size is changed. Not sure how to fix this outside of rebuilding the intro without `animation-delay`. #142 might fix this as a side effect, so I'll wait until that's done to do this.
