### ISSUE TITLE
Talking with sponsorship/donation team

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#15]

**Comment by rosszurowski** [comment]
Taylor put together a sponsorship spreadsheet, I'll link it here later. Just ping me for it.

**Comment by mileeco** [comment]
@CaeruIeus will be directing the design for sponsor/donate page now. @rosszurowski, can you provide him POCs to speak with sponsor team?

**Comment by rosszurowski** [comment]
@mileeco Sure. POCs for who's managing which companies are sponsoring and the requirements around that? [Marina](https://www.facebook.com/marina.rina.9469?fref=ts)'s probably the person to get in touch with. I'll ping @caeruIeus in Slack too.

**Comment by iamnbutler** [comment]
We passed along a doc to sponsors. Will follow up in further weeks.
