### ISSUE TITLE
Meet with video/documentary team

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#16]

**Comment by rosszurowski** [comment]
Talk with the branding team to figure out small bits of footage to start filming. Both for general site usage and of specific students.

The earlier we figure this out, the better.

**Comment by iamnbutler** [comment]
We had a discussion with Omar today about some of the video content ideas we had mentioned before. We can discuss these in the meeting we have today. If possible @rainkloud can you write down some of the topics discussed?

**Comment by iamnbutler** [comment]
Discussion with Omar:
- Interviews will be like 60 seconds
- Not everyone will have an interview (basically we can't require it)
- Design needs to consider not everyone having an interview
  @Emmersonic will post shortlist of questions

**Comment by Emmersonic** [comment]
https://docs.google.com/document/d/1ZpOcUGnWG2hHjcTsHvVXMW8Ijqiw2W2fT1E5ADT4l5E/edit?usp=sharing
