### ISSUE TITLE
Meet with social media team

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#17]

**Comment by rosszurowski** [comment]
Discuss options for moving beyond the single robotic social media account that summarizes the whole student body, maybe looking at how we can use hashtags or aggregation to let students represent themselves?

**Comment by rosszurowski** [comment]
Talked with this about the social media team. They didn't seem too keen on the idea of abandoning a single account for some good reasons. Things that aren't related to any specific student (event times, etc.) would be slightly strange to be announced by a particular person. More importantly: the lack of a single account would make it difficult for people to following or get persistent updates about the show; following a hashtag isn't a mechanic that's integrated into a lot of services.

That said, they were keen on the idea of promoting student work (blogs, podcasts, etc.).
