### ISSUE TITLE
Build database

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#21]

**Comment by rosszurowski** [comment]
I've started some work on this task in [this branch](https://github.com/ysdn-2016/api/tree/21-switch-to-postgres). The code works, but how to get Postgres running locally on everyone's computer is something that still needs to be figured out...

**Comment by rosszurowski** [comment]
Apparently just using `brew install postgres` works really well, and gives us a fairly consistent setup without the hassle of Vagrant/Docker environments. If everyone has a Mac, that's what we'll go with.

**Comment by rosszurowski** [comment]
Irrelevant now that we've moved to static site system
