### ISSUE TITLE
Investigate S3 uploads

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#23]
- Images
- Video?

**Comment by rosszurowski** [comment]
Any thoughts on how to keep images around for local development, but still out of the repo so we don't bog down Github and deploys?

**Comment by rosszurowski** [comment]
Maybe we could add the `content/` folder to `.gitignore`, and then sync it over S3 as part of the build step. That way, files are around for local builds, but then when we deploy we can do whatever shenaniganry we need.

Still, I'm not sure how image resizing and the like will fit into this...

**Comment by iamnbutler** [comment]
Yeah, we can probably use a hook for when we push to prod it runs whatever image deploy setup we figure out. I know there are some impressive rails image processing plugins, I'm sure there are probably some python or js based ones as well.

**Comment by rosszurowski** [comment]
Push to prod? You mean github pages? Keep in mind we moved away from the web app approach to things, so it's not as easy.

**Comment by iamnbutler** [comment]
Prod can = whatever. You can set up hooks on github to run anything base on which branches you push to if I remember correctly. https://developer.github.com/webhooks/ I'm not totally sure if it supports hooks based on branch though.

**Comment by rosszurowski** [comment]
Bumping into sprint 4. It'll be figured out this weekend because it needs to be demoable for Monday.

**Comment by rosszurowski** [comment]
Closed with the launch of [the admin panel](http://ysdn2016.com/admin/)
