### ISSUE TITLE
Add project queries to API

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#25]
Make projects accessible through the API.

Once this task is done, you should be able to access project data from queries like:

```
query {
  student(name: "Amy Chiu") {
    name,
    email,
    projects {
      title,
      description
    }
  }
}
```

and

```
query {
  projects {
    title,
    description
  }
}
```

Having this done will let Nate start messing around with pulling projects into a front-end and starting on the backend for galleries.

You'll need to create [a new model](https://github.com/ysdn-2016/api/tree/37b44dfc5aa81f01549657268414fba8c6e24c63/lib/models), and once you've defined that, you'll need to expose it through [the schema](https://github.com/ysdn-2016/api/blob/37b44dfc5aa81f01549657268414fba8c6e24c63/lib/schema.js), which is the publicly accessible interface. As for reference materials, check out the [GraphQL docs](https://github.com/graphql/graphql-js) and [this tutorial](https://medium.com/@clayallsopp/your-first-graphql-server-3c766ab4f0a2) to get a sense of how GraphQL works. Looking at the student model that's already there will also be helpful.

I've [added some tests](https://github.com/ysdn-2016/api/commit/37b44dfc5aa81f01549657268414fba8c6e24c63) to the `test/` folder. Just change the lines that say `it.skip('..')` to `it('..')` to enable them. Make your changes until they pass, and add any new tests that are relevant.

**Comment by iamnbutler** [comment]
I assume this is meant to be sprint 2. I'll mention it in the meeting before I reassign it.

**Comment by rosszurowski** [comment]
Made irrelevant thanks to #30
