### ISSUE TITLE
Sketches Round 2

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#28]
Continue refining sketches (wireframes, mockups, design sketches)

Homepage
- show description
- show details
- amouse bouche teasers of work/students

About Page (will it be needed?)

Navigation
- Search
- Filter

Student Index (Gallery)

Student Profile (Page)
- Cover Video
- Bio
- Links (Social Media, Contact Information, Portfolio, Resume)
- Integration with Grad Show (Set up meeting, Booth way-finding)
- Projects (Image, Summary)

Project Index (Gallery)
- \- Single vs. Multi-owner
- \- Surface metadata / tags / vertical type 

Project Page
- \- Regular
- \- Case Study
- \- Single vs. Multi-owner
- \- Different media types (Video, Images, Embeds)
- \- Where to next? (Students' other projects, related projected?)

Sponsor Show case
- Donation

Any Others
- 404
- General Container Template
- Curated Content (Articles/Skillshare)
- Inventory (reading list / items of interest)

Deliverables:
- 3 refined sketches for each
- 1 concept for bootstrap frontend

**Comment by rosszurowski** [comment]
It's important to also consider how the grad show "event" of the site fits in. How do you jump between the students/work and the event?

**Comment by mileeco** [comment]
Homepage: @iamnbutler for now, but we'll figure this out all together after we finish the rest of the pages.
Student index & profile: @Emmersonic and @rainkloud 
Project index & pages: @kvngco and @esokool
Sponsor/donate page: @CaeruIeus 
Event info page: @mileeco

Please have minimum of 3 different sketches uploaded by 11th.

**Comment by iamnbutler** [comment]
I only managed to work through one concept for this week. I can pick up the rest over the next few days or we can leave to do as a group depending on what we want to do for home.

**Comment by iamnbutler** [comment]
Homepage notes:
- For video:
  - Make it like an intro to the program
  - Show footage of people working, the labs etc
  - Need some marketing
  - 'Portal' feel is working
  - Event details are missing mostly
  - Link into categories better
  - Build it modularly so we can focus

**Comment by mileeco** [comment]
Event info notes:
- Showing values/benefits the person will get from attending the event (ex. highlighting previous year's grad shows, receiving updates)
- Sponsors list

**Comment by rainkloud** [comment]
Student Profile notes:
- Layout for concept three is the strongest
- Implement video and picture to concept 3
- Thumbnails over medium centric approach

**Comment by esokool** [comment]
<strong>Project profile notes:</strong>
- Pages for student / project profiles are separate
- Refine stand-alone project profile page w/ case study type project integration
- Explore more side-scroll layouts

**Comment by iamnbutler** [comment]
Closed.
