### ISSUE TITLE
Look into writing API

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#3]
Is there a good way for us to serve data to each of the projects we build as well as any on-site projects? Is it worth the time investment to write our own API?

**Comment by rosszurowski** [comment]
The way I understand this task is that we would have a separate server that hosts all our data (student info, project metadata, etc.) which all of our products leverage. So both the off-site and the on-site work would make calls to this API. This avoids privileging one product over others.

Is that what you mean by this task, or were you thinking something else?

**Comment by iamnbutler** [comment]
Yeah that is pretty much it. Pretty much is it worth the work or not.

**Comment by iamnbutler** [comment]
I was planning on discussing all these tasks at the meeting on wed, so we can discuss their contents and pivot based on our discussion then.

**Comment by rosszurowski** [comment]
Sounds good.

**Comment by iamnbutler** [comment]
I'm going to close this task, as I think the discussion can be consolidated into the backend tech task.
