### ISSUE TITLE
Backend Data Model

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#34]
Project
- Assets
- Large/Small project?
- Title
- Owner
- Markdown blob
- Course
- Year
- Category
  - Subcategory/Context
- Awards
  Questions:

```
- How to style captions, etc
- External URL
```

Students
- Name
- Profile Image
- Video?
- Biography
- Links
  - Portfolio Site
  - Social
- Resume
- Projects
- Groups

**Comment by rosszurowski** [comment]
Closing this because it already exists in #24
