### ISSUE TITLE
Evaluate previous year's grad show sites

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#4]

**Comment by mileeco** [comment]
Grab us local files from Loris pls @iamnbutler (Delve '13, Facets '14, and Made '15, in case they go down again)

**Comment by rosszurowski** [comment]
2015, Made — http://ysdnmade.it
2014, Facets — http://ysdnfacets.com/
2013, Delve — http://ysdngradshow.com/2013
2012, Pique — http://pique2012.com
2011, &Co — http://ysdnand.co/
2010, YSDN10 — http://ysdn10.com
2009, Wanderlust — http://apassionatecuriosity.com/
2008, Splice

**Comment by rainkloud** [comment]
I can help with this as well!

**Comment by kvngco** [comment]
I can take a quick look, too.

**Comment by mileeco** [comment]
@iamnbutler any update on local files for previous gradshow sites? Facets (2014), Delve (2013), and Pique (2012) are broken.

**Comment by iamnbutler** [comment]
I actually havent been in TEL since Wed! I can ask about it tomorrow.

**Comment by iamnbutler** [comment]
Discussed this with Loris, it seems that there is no old gradshow data hosted on digital locker.

**Comment by mileeco** [comment]
Screenshots & notes up on Drive. Files can be found on Drive: Off-site Design > Research. We'll discuss them during the meeting later today

**Comment by mileeco** [comment]
Notes and screenshots can be found here:
https://drive.google.com/drive/u/0/folders/0Bz4MlLGfH1VycldwaGVPNUMyOEE
