### ISSUE TITLE
Figure out how to get content

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#40]
Figure out how we will get content (projects, etc) from students for site

**Comment by chloecatastrophe** [comment]
Is there a way to add Ian to this too?

**Comment by chloecatastrophe** [comment]
Some preliminary thoughts:
- submission through dropbox
- submission through Sheridan or York servers
- create a website and accept submissions through that

**Comment by rosszurowski** [comment]
Assigning then unassigning seems to have subscribed him to notifications from this thread, so yes? Github does only allow one assignee at a time.

Anyways, @chloecatastrophe and @CaeruIeus, do you have time late next week (say, Friday at 5:30pm) to talk about what this entails? I'll be able to fill you in about how the back-end of the site is operating and what final format we'll need the content to be in.

The way I see it, there's two approaches we can take:
- Website for submissions (hard set-up, easy collection)
- Manual collection (easy set-up, hard collection)

**Comment by chloecatastrophe** [comment]
@rosszurowski Do you want to do an online meeting, at York, or at Sheridan?

I can meet next Friday, November 20 after 4:30. I'll already be at Sheridan if you want to meet there, otherwise I can bus to York or we can do Skype/Google Hangouts etc.

I personally am leaning towards a website for submissions but I'd definitely like to hear what you have to say about what this entails.

**Comment by rosszurowski** [comment]
@chloecatastrophe: Let's just do an online meeting. Should be fine.

I think a submission website would be the best experience for everyone, it's just a matter of how difficult it would be to develop (image uploads, etc).

**Comment by rosszurowski** [comment]
We met and decided that we'll be using the [admin interface](http://ysdn-2016.github.io), with another option (Google Forms, Wufoo) prepared as a backup. I've assigned @chloecatastrophe to #43 to track progress on this front.
