### ISSUE TITLE
Student Index Page (List View)

### ISSUE THREAD

**Issue by Emmersonic** [ysdn-2016/ysdn-2016.github.io#49]
Index of student names

**Comment by iamnbutler** [comment]
![screenshot 2016-01-23 18 08 42](https://cloud.githubusercontent.com/assets/1714999/12533398/eee3ee34-c1fc-11e5-96a1-a9fc8e9aadd7.png)
Current progress of student index dev. List view almost done.

TODO:
- Work filter
- Search Filter
- Grid View

Blockers:
- Need a way to get student work categories with swig tags @rosszurowski

**Comment by iamnbutler** [comment]
Closing out the gridview task in favour of consolidating into this one.

**Comment by rosszurowski** [comment]
This page is going through a re-thinking. Plus we're tracking things [in Trello](https://trello.com/b/QBjrsdYN/off-site-tasks) now anyways. Closing this out.
