### ISSUE TITLE
Microsite exploration & sketches

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#5]
What are some of the microsites we could build that would be exciting and useful for other designers? For the public? Explore some of the possibilities (keeping in mind some of the brainstorming we have already done.)

Brainstorming doc: https://docs.google.com/document/d/1G2Hd5g3ri2TU-dvgOGpL4ASziYh6wpC63j69Ofbtobc/edit?usp=sharing

**Comment by mileeco** [comment]
Focusing on figuring out the experience for the main site for now, will focus on this during sprint 2.

**Comment by iamnbutler** [comment]
Moving this to sprint 4. I want us to focus on getting the main site rolling before we explore other stuff.

**Comment by iamnbutler** [comment]
I don't think we will have time for this. If we do we will address these as individual tasks later in the process.
