### ISSUE TITLE
YSDN 2016 Dev Brand

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#6]
What's the point of having an awesome site if we don't look fabulous while doing it? Let's come up with a quick, kickass brand that we can show off every time we post something on Dribbble, Twitter, Facebook and elsewhere.

**Comment by iamnbutler** [comment]
![ysdn 2016 0 4 3x](https://cloud.githubusercontent.com/assets/1714999/10440930/70a2e868-7111-11e5-88ce-b4fb3e38aebc.png)

This is the icon I came up with, but it is pretty lame. I'm sure we can do better. You can find the sketch files in the ysdn-2016-meta repo in the ysdn-2016 organization.

**Comment by iamnbutler** [comment]
If we decide not to do anything with this task then @mileeco leave a comment here and close it out.

**Comment by rosszurowski** [comment]
![image](https://cloud.githubusercontent.com/assets/303731/10654178/0df2f0e8-7835-11e5-92db-036cc9c899bf.png)

**Comment by huntercaron** [comment]
nice

**Comment by rosszurowski** [comment]
✨
