### ISSUE TITLE
Use an SVG for the "Come Meet the Cast" section on the home page

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#69]
The png looks kind-of blurry, even on my non-retina screen.

**Comment by iamnbutler** [comment]
Cool, I didn't have the time to make an SVG from scratch and exporting from sketch gives this:
![screenshot 2016-03-20 06 53 38](https://cloud.githubusercontent.com/assets/1714999/13904019/7f510e2e-ee68-11e5-8b25-b8fffa4dde98.png)

**Comment by iamnbutler** [comment]
This was completed a while ago, looks like it was never closed out.
