### ISSUE TITLE
Main Site Design Sketches

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#7]
Let's get a bunch of ideas for each of the following. Sketches are more than just a scribble on paper! If presenting paper sketches, make sure they have been refined, if presenting wireframes, they should be more than just boxes.

Go crazy with your ideas! We can refine and scale back when meeting to discuss them, but don't count anything out at the beginning. Feel free to bring others in to do sketches as well.
- Gallery
- Student Profile
- Student Index
- "Home" Page
- Sponsor Showcase
- Any Others

**Comment by rainkloud** [comment]
@ramisk Student Profile, Student Index, Gallery

**Comment by kvngco** [comment]
@kvngco gallery, profile, index

**Comment by Emmersonic** [comment]
@emmersonic Student Profile, Student Index

**Comment by mileeco** [comment]
@mileeco Profile, Sponsors

**Comment by esokool** [comment]
Sponsor showcase, gallery, I can also explore different nav ideas

**Comment by Emmersonic** [comment]
Some of my sketches :)

![1](https://cloud.githubusercontent.com/assets/6530910/10834238/0f6a06a2-7e6e-11e5-9804-29e34314bacc.png)
![2](https://cloud.githubusercontent.com/assets/6530910/10834241/0f6f7588-7e6e-11e5-98e7-3c0f230626b1.png)
![3](https://cloud.githubusercontent.com/assets/6530910/10834239/0f6b1588-7e6e-11e5-837b-57236acfc28d.png)
![student index](https://cloud.githubusercontent.com/assets/6530910/10834240/0f6e0c20-7e6e-11e5-9068-f5a1262aa541.png)

**Comment by mileeco** [comment]
Files can be found here: https://www.dropbox.com/sh/sy94jpn2ssygasc/AABZ4V20V-E8kCgHS_NvO36va?dl=0. Dropbox > Off-site > Main Site Design Sketch

**Comment by iamnbutler** [comment]
I did a profile sketch:
![nate-profile-sketches](https://cloud.githubusercontent.com/assets/1714999/10835173/37ecd8a4-7e76-11e5-9fc0-d37b60d43faa.png)

**Comment by iamnbutler** [comment]
Sketches Drive link:
https://drive.google.com/folderview?id=0BwqC5gxVJvtXTENiVG16azlpdk0&usp=sharing

**Comment by iamnbutler** [comment]
Closing this out, will break down in new tasks for sprint 2.
