### ISSUE TITLE
Closing event panel doesn't update url

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#70]
Clicking event panel takes you to event:
![screenshot 2016-03-20 06 54 54](https://cloud.githubusercontent.com/assets/1714999/13904026/adbfd218-ee68-11e5-9c49-88c3b6305b1c.png)

But on closing the url isn't updated (so if you refresh it takes you back to event)
![screenshot 2016-03-20 06 54 57](https://cloud.githubusercontent.com/assets/1714999/13904030/c2745db4-ee68-11e5-8a3f-a5d6601e8400.png)

**Comment by Emmersonic** [comment]
Looks like this has been resolved.
