### ISSUE TITLE
The Case of the Phantom Images

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#72]
I'll leave a note here for anyone I run across with missing photos.

**Comment by iamnbutler** [comment]
Karmen Ng is missing a profile photo.
![screenshot 2016-03-20 08 40 03](https://cloud.githubusercontent.com/assets/1714999/13904449/8b0a0fae-ee77-11e5-8fd1-d8bc1ce046e8.png)

**Comment by iamnbutler** [comment]
There seems to be a clipping issue with Tannaz Sotoudehnema's student index image/animation:
<img width="285" alt="screenshot 2016-03-20 08 48 37" src="https://cloud.githubusercontent.com/assets/1714999/13904488/aca54f10-ee78-11e5-8e3d-be94585344ae.png">

**Comment by rosszurowski** [comment]
👻😱

**Comment by rosszurowski** [comment]
Interesting. It's like the build process missed Karmen's image, because it's working for me locally.

**Comment by rosszurowski** [comment]
Resynced and it looks like hers is up now.

**Comment by rosszurowski** [comment]
I think this is resolved now.
