### ISSUE TITLE
Home Page: Work samples are sometimes duplicates

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#73]
![screen shot 2016-03-20 at 9 02 51 am](https://cloud.githubusercontent.com/assets/303731/13904550/16546d72-ee7b-11e5-9267-f32e464197b2.png)

This likely affects the project footer too.

**Comment by iamnbutler** [comment]
Yup. Right now this is 2 loops, a take(1) and take(2), this is a temp solution. I'm still not totally sure how to do this page. I'll get back at it sometime today.

**Comment by iamnbutler** [comment]
I can probably just use a take(3) loop and use :nth-child to build the columns. I'll try this out later.

**Comment by iamnbutler** [comment]
Fixed with new homepage work system
