### ISSUE TITLE
Student Index is slow to load

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#79]
As per [Kevin's findings](https://ysdn-2016.slack.com/archives/off-site-design/p1459824258000264)

**Comment by rosszurowski** [comment]
I've pushed an improvement in https://github.com/ysdn-2016/ysdn-2016.github.io/commit/987b0b59f7fec98761288fdc1d6fd6768a804455. @kvngco, mind confirming that it helped?

**Comment by kvngco** [comment]
LIKE BUTTER!!!

**Comment by iamnbutler** [comment]
I get mega lag when I scroll on the student index page. It seems to get worse the longer the page is open.
