### ISSUE TITLE
Investigate using video

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#8]
Find some examples of video that are used really well. Then make some sketches/mockups/prototypes of how we could use video in our own site.

**Comment by rosszurowski** [comment]
Once this is figured out more, someone should be designated the _video contact person_ for the team and coordinate with Omar and Shakura (the video people in the ops team) to get things filmed. Even if we end up doing it ourselves, I think it'd be considerate to at least consult with them.

**Comment by rainkloud** [comment]
I can help with researching what to film and how to treat the videos online.

**Comment by iamnbutler** [comment]
Parse uses video pretty well here in their customers header: https://parse.com/customers.
It's pretty nice how it tastefully interacts with the header.

**Comment by iamnbutler** [comment]
These guys have a pretty nice video intro: http://www.olloclip.com/. A similar kinda intro video could be explored.

**Comment by rainkloud** [comment]
will be implementing them into sketches if appropriate :)

**Comment by rainkloud** [comment]
resovled
