### ISSUE TITLE
Arrow in the ribbon should be reversed

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#80]
Right now on staging the arrow is pointing down, not up. Think it should be pointing up to indicate there's more above. If not I'd assume it's just pointing the contents below. 

Reference this: https://projects.invisionapp.com/d/main#/console/5888771/147930237/preview

**Comment by rosszurowski** [comment]
Fixed in https://github.com/ysdn-2016/ysdn-2016.github.io/commit/690c147c7fedc83cd2ffebad6f5e7bfee69da021
