### ISSUE TITLE
Unceremonious entry for student profiles

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#81]
Student profiles are like the heart of the site and yet, right now, the student picture loads kind-of slowly and the shapes are just already floating there.

It'd be great to dramatically animate things in. This will also help with the perception of the loading.

**Comment by iamnbutler** [comment]
Added a basic sequential fade animation for the portrait and shapes. This doesn't seem to fix the problem  of portraits loading last though. Is there a way to prioritize loading them? 

Could we start loading them from when the user hits the student index in the background?

**Comment by kvngco** [comment]
This relates to #79. Takes a good few seconds for images to load, even when slowly scrolling on mobile.

**Comment by rosszurowski** [comment]
This above comment & a better intro has been tackled so I'm closing this out.
