### ISSUE TITLE
Remove logo in nav for home page (mobile)

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#83]
![image](https://cloud.githubusercontent.com/assets/8468476/14275052/f2386c12-fae2-11e5-8721-9be43fbfddad.png)

There really isn't any reasons to have the logo at the top for home page on mobile version. We need it for desktop to show the nav but for mobile we have the nav below.

I'd also suggest removing a few rows of dots so that the logo is the grid is brought up to the middle. It's cropped right now.

**Comment by iamnbutler** [comment]
This is a leftover from the nav being at the top of the page. Will fix now.

**Comment by iamnbutler** [comment]
This might be more complicated than I initially thought. I didn't realize the event ribbon and mobile header are inside the `<header>` tag. I'll come back to this when I can check in with Ross.
