### ISSUE TITLE
Mobile navigation disable scroll

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#84]
![image](https://cloud.githubusercontent.com/assets/8468476/14275095/481f698c-fae3-11e5-8b19-e124f43494b2.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14275096/482eaa3c-fae3-11e5-8ae2-5fddc9847aaa.png)

I noticed that you can still scroll the page when the navigation is open. We should have it so that the nav and the ribbon dismiss once the user taps outside to scroll

**Comment by kvngco** [comment]
we can do a slight dark overlay on the body behind to help cue that you can't interactive with the page once the menu is open, and if you do click on overlay, the menu collapses again.
