### ISSUE TITLE
Fix type treatment / spacing on home page (mobile)

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#85]
![image](https://cloud.githubusercontent.com/assets/8468476/14275151/a53599ca-fae3-11e5-8fa4-6585f1d7dae5.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14275152/a53c812c-fae3-11e5-8891-57ca77b48c31.png)

The line-height is different for "see what we've been up to behind the scenes". Tighten it to match the line-height in all other copy

For "Follow along on..." sentence, add some padding above (maybe the same amount of padding as bewlow?"

**Comment by iamnbutler** [comment]
Fixing this now. When you get a chance @mileeco take a look at the updated line height and spacing and make sure it matches what you are thinking.
