### ISSUE TITLE
Shapes not loading properly on mobile

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#86]
![image](https://cloud.githubusercontent.com/assets/8468476/14275266/41926b2c-fae4-11e5-9af0-a734a05441cc.png)
Looks like the blend mode isn't working as it should. ^ Safari app

**Comment by iamnbutler** [comment]
![screenshot 2016-04-07 05 29 34](https://cloud.githubusercontent.com/assets/1714999/14346785/bf3c9388-fc81-11e5-8b33-1e33d94eafb2.png)
Fixed by fixing SVGs with some cutting up shape and masking
