### ISSUE TITLE
Divider line broken on case study pages (mobile)

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#88]
![image](https://cloud.githubusercontent.com/assets/8468476/14285349/1fcfd5a8-fb19-11e5-96f3-c8afbfc4b3e1.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14285370/38e95b18-fb19-11e5-8e5c-8419a01bb481.png)

The divider line is overlapping with the text, and theres a big gap in between. Can we fix this so the divider line falls below (reduce the gap too?)

**Comment by Emmersonic** [comment]
Fixed
