### ISSUE TITLE
Logo on mobile site

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#89]
Maybe this needs some discussion instead, but adding it as an issue so we don't forget
Right now it feels really strange to have the logo sitting on the top left corner of every page, pushing down all the content to the middle. This makes all the pages seem broken.

Three possible ways to handle this:
1) Reduce the size of the logo, and shorten the height of the padding around the logo so that it pulls the content up
2) Center align the logo, and have a subtle line underneath to separate it from the contents on the page
3) Removing logo and putting the logo and the home link in the nav instead

I'm more leaning towards option 3 so it doesn't take up space. Left alignment feels a little strange to me with nothing on its right... it feels like it's floating.

![image](https://cloud.githubusercontent.com/assets/8468476/14285685/807efda6-fb1a-11e5-8fd2-953b993051f7.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14285686/808b9fac-fb1a-11e5-9e77-8c490dd39c0b.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14285687/808c7d14-fb1a-11e5-8be5-9a3e79b5d2aa.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14285688/808d239a-fb1a-11e5-8785-91f3378542e0.png)

**Comment by rosszurowski** [comment]
Left-aligned in 98dbeea. Needs some review, particularly the sponsors page (which I kept centred because the logos were centred) and the student index page when there are no search results.

**Comment by mileeco** [comment]
Ok just went through and they all look good to me! @kvng check this when you have a min

I wonder if it's weird to have different header treatments for about and sponsors page. If it isn't, let's keep it.

The shapes look a bit odd in sponsors page... they're a bit too close I think. I'll create this as another issue tho

**Comment by iamnbutler** [comment]
Looks good from what I can see. Gunna close this out.
