### ISSUE TITLE
Frontend Tech Discussion

### ISSUE THREAD

**Issue by iamnbutler** [ysdn-2016/ysdn-2016.github.io#9]
Co-ordinate with backend guys, what will the frontend code be written in? Plain HTML, React, Angular? Sass or SCSS? Etc. Doesn't need to be complicated, just make sure everyone is on the same page.

**Comment by iamnbutler** [comment]
This task may get bumped to the next sprint, as we will probably need to know what we are working with on the backend first. (If we are working in rails, we will use the built-in views + haml perhaps, etc.)

**Comment by iamnbutler** [comment]
For the backend we will be using a static site generator, which will make frontend development exceedingly easy. Sass & Compass are viable options, other technologies may be considered.

**Comment by rosszurowski** [comment]
This seems to be sorted out; closing.
