### ISSUE TITLE
Student profile shapes

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#92]
The shapes around the student photo feel odd and imbalanced. Can we change it back to what's in the mock: https://projects.invisionapp.com/d/main#/console/5888771/136936739/preview

![screenshot-staging ysdn2016 com_2016-04-04_17-33-55](https://cloud.githubusercontent.com/assets/8468476/14286232/617c2e0e-fb1c-11e5-950d-2c51c6632811.png)
![12966168_10153947242381163_306932093_n](https://cloud.githubusercontent.com/assets/8468476/14286278/81e5c826-fb1c-11e5-9e02-32a6a9b24cac.jpg)

**Comment by iamnbutler** [comment]
This should be fixed. I'm not sure where that extra space at the top came from but I fixed it. I'm tagging @rosszurowski just in case it has something to do with the header and was supposed to stay.

**Comment by rosszurowski** [comment]
@iamnbutler Yup, that's on me. I can fix it.
