### ISSUE TITLE
Regular project pages missing divider line before footer (mobile)

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#93]
Missing divider line!!!

![image](https://cloud.githubusercontent.com/assets/8468476/14286567/83033a4e-fb1d-11e5-96ab-8a0d7de85f6d.png)
![image](https://cloud.githubusercontent.com/assets/8468476/14286568/83048250-fb1d-11e5-97ea-72066ba5e624.png)

**Comment by Emmersonic** [comment]
I think this is on Desktop too

**Comment by Emmersonic** [comment]
Fixed! (Desktop & Mobile)
