### ISSUE TITLE
Reg project student name 15px -> 16px

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#94]
Can we change it to 16px so it matches the rest of the site, thanks!

![screenshot-staging ysdn2016 com_2016-04-04_17-40-13](https://cloud.githubusercontent.com/assets/8468476/14286729/157ddb5e-fb1e-11e5-9672-178b7d08af6b.png)

**Comment by Emmersonic** [comment]
Fixed!
