### ISSUE TITLE
Intro shapes animation

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#95]
Hoping this can be tackled before the launch. I was wondering if the shapes in the intro can appear at different times instead, instead of them all sliding in together? (reference mocks on InVision: https://projects.invisionapp.com/d/main#/console/5888771/131770112/preview) It feels weird that all the shapes are sliding in at once, it's like sliding in a layer with all the shapes pasted on it...

It'd be ideal to have them slide in from different angles, like how this site has it: http://ysdn2016.com/shapes/. If not just showing shapes at different times (popping in) would be fine too

**Comment by iamnbutler** [comment]
Same as #99. Will work from that one.
