### ISSUE TITLE
Mobile Homepage Interactive & Motion H-Scroll Shows Information Design instead

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#97]
![screen shot 2016-04-05 at 16 21 19](https://cloud.githubusercontent.com/assets/3757807/14296936/72fea584-fb4a-11e5-836a-9bcc923d1579.png)

information design works instead of right category

**Comment by rosszurowski** [comment]
Wow, this is easy to miss. Great catch! Fixed in 370906d
