### ISSUE TITLE
Elements (Text, Shapes, Buttons) off alignment within grid

### ISSUE THREAD

**Issue by kvngco** [ysdn-2016/ysdn-2016.github.io#98]
Homepage – Meet The Cast
· two extra dots on right
![screen shot 2016-04-05 at 16 22 10](https://cloud.githubusercontent.com/assets/3757807/14297041/f07f2e0c-fb4a-11e5-9e98-f050f0f59493.png)

Work Index – All Work
· two extra dots on right
![screen shot 2016-04-05 at 16 22 19](https://cloud.githubusercontent.com/assets/3757807/14297052/fcdf96c8-fb4a-11e5-8134-6a69ae999bb4.png)

Work Index – Physical
· vertical alignment off (baseline sits on dot grid)
![screen shot 2016-04-05 at 16 22 32](https://cloud.githubusercontent.com/assets/3757807/14297082/2b5138f4-fb4b-11e5-81d4-f10b3d5e4716.png)

Work Index – Communication
· rogue triangle off grid
· vertical alignment off (baseline sits on dot grid)
![screen shot 2016-04-05 at 16 22 49](https://cloud.githubusercontent.com/assets/3757807/14297084/2f89c094-fb4b-11e5-87f1-6587ff09bc3f.png)

**Comment by iamnbutler** [comment]
I'll grab the homepage one.
